### ISSUE TITLE
bug: Geometry sent from Rhino not visible

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-powerbi-visuals#11]
## Description

Geometry sent from Rhino received successfully but can not be viewed in 3D Viewer Visual.

## Expected Behaviour

View the geometry in 3D Viewer Visual, regardless of its source application.

## Steps to reproduce

1. Receive below stream in PowerBI👇
2. Add 3D Viewer Visual
3. Connect Stream URL and Object ID inputs.
4. You will not be able to view any geometry in the Viewer.

## Streams/Commits Used

[https://latest.speckle.dev/streams/5ae0332cc7/branches/rhino](https://latest.speckle.dev/streams/5ae0332cc7/branches/rhino)

## Screenshots

![PBIDesktop_b0vzF8gfHi](https://user-images.githubusercontent.com/51519350/203101509-41a23a43-a214-43ab-a4f3-a9f282cbfec9.png)

**Comment by AlanRynne** [comment]
Same as #10, Viewer is not prepared yet to handle authentication via PowerBI, so any private streams will not load.
