### ISSUE TITLE
Figure out authentication strategy for visual

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-powerbi-visuals#13]
From #10 and #11

Viewer cannot fetch data from private streams due to it lacking access to the Data Connector token.

Not sure if this is something that can be provided, or if we're going to have to re-invent the wheel on this one.

Possible options:
- Have the Data Connector pass the token to the Visual (not sure if it is doable)
- Have the visual receive the actual objects from the data connector instead of fetching them

**Comment by AlanRynne** [comment]
Passing the data to the token is not a viable alternative. I've had chat with Alex about option 2, which is not going to be immediately doable.

**Comment by AlanRynne** [comment]
After fixing #30 we can enable the viewer to do OAuth on it's own.

**Comment by AlanRynne** [comment]
This is now unblocked :D

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
