### ISSUE TITLE
Reload Visual When filtering

### ISSUE THREAD

**Issue by gjordanp** [specklesystems/speckle-powerbi-visuals#19]
## What package are you referring to?
Alpha 5

## Describe the bug
Trying Alpha 5 release, I noticed that loading is much faster than before (batch loading). Great Improvement!! Thanks
But when I filter data, it is like those elements are removed from the 3D visual, and when I undo the filter, It start loading again (for those filtered elements). I think normal behavior should be to "Gray Out" filtered elements from visualization, so you don't have to fetch elements again. (Just fetch the first time you open Power BI).

Best Regards

## To Reproduce

 Try filtering data in any project

## Screenshots

![screenshot1](https://user-images.githubusercontent.com/67670790/216311251-46d9d1f8-8f31-44c9-bf0f-8bb7fa2d7199.png)
![screenshot2](https://user-images.githubusercontent.com/67670790/216311270-ef4219c1-4639-4bec-ba8b-72e1c8da6864.png)
![screenshot3](https://user-images.githubusercontent.com/67670790/216311276-b61ba609-e3ce-4f8c-b78a-df7645ff5c65.png)

**Comment by AlanRynne** [comment]
hey @gjordanp!

Sadly, not sure we can have any control over this. When you filter data in PowerBI, those data objects are actually **removed** from the input of the viewer, so the viewer is no longer receiving them.

There is technically no difference, with regards to PowerBI, between swapping the data input for a completely different one, or just filtering 2 objects out of 5000.

PowerBI will consider this a "data change" event, and will provide the **full list** of objects that are connected.
The viewer has no knowledge of what filters are active at any given time, so we can't really use ghosting in this particular case.

I agree this would be rather nice, but not sure what can be done about it with the current PowerBI API.

**Comment by AlanRynne** [comment]
Hi @gjordanp! Just letting you know that this has been fixed and will be included in the next release ;)

We've changed the way the visual loads the objects in favor of loading the original commit object (which contains everything), so now filtering should be super fast too!

**Comment by gjordanp** [comment]
Nice, this will be a significant improvement. 
Thanks a lot!

**Comment by AlanRynne** [comment]
Closing this for now! If you find any loading issues when filtering now, feel free to reopen :)
