### ISSUE TITLE
Inputs / Colors / Slicers

### ISSUE THREAD

**Issue by WalidAnane** [specklesystems/speckle-powerbi-visuals#22]
Helloo :) 

I noticed a couple of things while trying the PowerBI connector:

- Slicers do not affect the model
- Colors are not/no longer functional no matter what data is loaded
- Changing inputs (URL, object ID, etc.) involves deleting and reloading the viewer.

Any fixes in perspective?

**Comment by AlanRynne** [comment]
Hi Walid! Sorry I missed this issue.

I've been working on some heavy improvements that we're releasing in the coming days which should fix the first and second issue.

As for the third item, I can't reproduce this anymore so I'm guessing it's fixed but let us know if it hasn't once the new release comes out!

**Comment by AlanRynne** [comment]
Hey @WalidAnane, do let us know if you're still experiencing this with the latest PowerBI version. I think this should have been fixed.

**Comment by WalidAnane** [comment]
Fixed ;)
