### ISSUE TITLE
Improved selection and drilldown/up support

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-powerbi-visuals#31]
Current selection logic of the visual is "Per Object", but this could be modified to be "per category" or "per grouping".

This would align with how other visuals do selections (which by default will select the entire grouping).

Furthermore, we could add `drilldown` support, which in essence means you can:
- Select a single object and "drill up" to select it's parent category
- Select a category and "drill down" to select individual children

My understanding of this may be flawed and should require prior scoping.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
