### ISSUE TITLE
Store viewer state using LocalStorage API

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-powerbi-visuals#33]
PowerBi visuals have a LocalStorage API that allows to save some data. This API also allows for multiple visuals of the same type to share that localStorage data.

https://learn.microsoft.com/en-us/power-bi/developer/visuals/local-storage

This could be potentially used to sync up store the "last known view" of a report for a given user, sync up multiple viewer cameras, and other neat stuff... although it may be a pipe-dream

For now, we could just store some info on the viewer state so that hard reloads wouldn't reset your last known view.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
