### ISSUE TITLE
Add support for coloring based on Base object prop value

### ISSUE THREAD

**Issue by AlanRynne** [specklesystems/speckle-powerbi-visuals#4]
I've seen this done in other PowerBI fancy viewers, this would be a nice feature.

This must be scoped first

**Comment by AlanRynne** [comment]
This is already possible! :)

**Comment by fraguada** [comment]
@AlanRynne is this a 2.10 issue?

**Comment by AlanRynne** [comment]
This was a placeholder issue for this feature but I had forgotten to close it. There feature has been there since the original alpha release of the viewer
