### ISSUE TITLE
Bidirectional selection and Coloring not working on 2.15-rc 3D Viewer

### ISSUE THREAD

**Issue by gjordanp** [specklesystems/speckle-powerbi-visuals#49]
Hi, 
I'm trying the last 3D Viewer for Power BI, and selecting from 3D model work fine
![image](https://github.com/specklesystems/speckle-powerbi/assets/67670790/f52056be-dbd6-4668-8d75-b67a54832505)
But selecting from other visual wont get updated in model.
![image](https://github.com/specklesystems/speckle-powerbi/assets/67670790/ce06d1a2-c056-48f6-8340-49e22519952b)

Also the option for Color By, it wont work
![image](https://github.com/specklesystems/speckle-powerbi/assets/67670790/ed3e4a51-8fa2-4aac-9fc3-937430f60883)

I have atached my PowerBI file on this link.
https://spoerering-my.sharepoint.com/:u:/g/personal/gjordan_btd_cl/EYgyWCyMFQNKvOkRot5iC1MBXNo2uimQvmqOITV_TISkTQ?e=rgPfil

Best regards

**Comment by bimgeek** [comment]
Hey @gjordanp, 

The link you provided has expired. Could you please share the file again?

**Comment by bimgeek** [comment]
Hey @gjordanp ,

I think we found what's wrong. This problem only occurs when Tooltip input not set. Can you try setting tooltip input and see if that fixes it?
